hello_page:
      path: /hello
      controller: App\Controller\DefaultController::hello

Boutique:
      path: /boutique
      controller: App/Controller/BoutiqueController::index

contact:
      path: /contact
      controller: App\Controller\DefaultController::contact